<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tb_clase')->insert([
            ['id_clase' => 1, 'id_grupp' => 1, 'nombre_clase' => 'Clase 1: Epidendrum especie con racimo'],
            ['id_clase' => 2, 'id_grupp' => 1, 'nombre_clase' => 'Clase 2: Epidendrum especie con panícula'],
            ['id_clase' => 3, 'id_grupp' => 1, 'nombre_clase' => 'Clase 3: Epidendrum tipo Oerstedella'],
            ['id_clase' => 4, 'id_grupp' => 1, 'nombre_clase' => 'Clase 4: Epidendrum tipo caña'],
            ['id_clase' => 5, 'id_grupp' => 1, 'nombre_clase' => 'Clase 5: Barkeria'],
            ['id_clase' => 6, 'id_grupp' => 1, 'nombre_clase' => 'Clase 6: Encyclia'],
            ['id_clase' => 7, 'id_grupp' => 1, 'nombre_clase' => 'Clase 7: Prosthechea'],
            ['id_clase' => 8, 'id_grupp' => 1, 'nombre_clase' => 'Clase 8: Rhyncholaelia y Brassavola'],
            ['id_clase' => 9, 'id_grupp' => 1, 'nombre_clase' => 'Clase 9: Laelias, Schomburgkia, Caularthron y Myrmecophila'],
            ['id_clase' => 10, 'id_grupp' => 1, 'nombre_clase' => 'Clase 10: Híbridos de Encyclia, Laelia, Broughtonia, etc.'],
            ['id_clase' => 11, 'id_grupp' => 1, 'nombre_clase' => 'Clase 11: Arpophyllum, Isochilus, Coelia, Bletia'],
            ['id_clase' => 12, 'id_grupp' => 1, 'nombre_clase' => 'Clase 12: Elleanthus, Sobralia especies e híbridos'],
            ['id_clase' => 13, 'id_grupp' => 1, 'nombre_clase' => 'Clase 13: Scaphyglottis, Jaquinella, Polystachya, etc.'],
            ['id_clase' => 14, 'id_grupp' => 2, 'nombre_clase' => 'Clase 14: Guarianthe especie'],
            ['id_clase' => 15, 'id_grupp' => 2, 'nombre_clase' => 'Clase 15: Guarianthe híbrido con Cattleyas'],
            ['id_clase' => 16, 'id_grupp' => 3, 'nombre_clase' => 'Clase 16: Cattleya de 1 o 2 hojas especies'],
            ['id_clase' => 17, 'id_grupp' => 3, 'nombre_clase' => 'Clase 17: Cattleya híbridos de todos colores'],
            ['id_clase' => 18, 'id_grupp' => 3, 'nombre_clase' => 'Clase 18: Híbridos de Encyclia, Broughtonia con Cattleya'],
            ['id_clase' => 19, 'id_grupp' => 4, 'nombre_clase' => 'Clase 19: Lycaste virginalis fo. Alba'],
            ['id_clase' => 20, 'id_grupp' => 4, 'nombre_clase' => 'Clase 20: Lycaste virginalis fo. Virginalis'],
            ['id_clase' => 21, 'id_grupp' => 4, 'nombre_clase' => 'Clase 21: Lycaste virginalis fo. Superba'],
            ['id_clase' => 22, 'id_grupp' => 4, 'nombre_clase' => 'Clase 22: Lycaste guatemalensis'],
            ['id_clase' => 23, 'id_grupp' => 4, 'nombre_clase' => 'Clase 23: Lycaste cruenta = Selbyana cruenta'],
            ['id_clase' => 24, 'id_grupp' => 4, 'nombre_clase' => 'Clase 24: Lycaste cochleata = Selbyana cochleata'],
            ['id_clase' => 25, 'id_grupp' => 4, 'nombre_clase' => 'Clase 25: Lycaste deppei'],
            ['id_clase' => 26, 'id_grupp' => 4, 'nombre_clase' => 'Clase 26: Lycaste dowiana'],
            ['id_clase' => 27, 'id_grupp' => 4, 'nombre_clase' => 'Clase 27: Lycaste lasioglossa'],
            ['id_clase' => 28, 'id_grupp' => 4, 'nombre_clase' => 'Clase 28: Otras especies de Lycaste'],
            ['id_clase' => 29, 'id_grupp' => 4, 'nombre_clase' => 'Clase 29: Sudamerlycaste'],
            ['id_clase' => 30, 'id_grupp' => 4, 'nombre_clase' => 'Clase 30: Anguloa especies e híbridos'],
            ['id_clase' => 31, 'id_grupp' => 4, 'nombre_clase' => 'Clase 31: Lycaste híbrido natural o artificial primario'],
            ['id_clase' => 32, 'id_grupp' => 4, 'nombre_clase' => 'Clase 32: Lycaste híbridos complejos'],
            ['id_clase' => 33, 'id_grupp' => 4, 'nombre_clase' => 'Clase 33: Camaridium'],
            ['id_clase' => 34, 'id_grupp' => 4, 'nombre_clase' => 'Clase 34: Heterotaxis'],
            ['id_clase' => 35, 'id_grupp' => 4, 'nombre_clase' => 'Clase 35: Rhetinantha aciantha y similares'],
            ['id_clase' => 36, 'id_grupp' => 4, 'nombre_clase' => 'Clase 36: Maxillariella'],
            ['id_clase' => 37, 'id_grupp' => 4, 'nombre_clase' => 'Clase 37: Maxillarias sudamericanas especie e híbrido'],
            ['id_clase' => 38, 'id_grupp' => 4, 'nombre_clase' => 'Clase 38: Maxillaria tipo sudamericana especie e híbrido'],
            ['id_clase' => 39, 'id_grupp' => 4, 'nombre_clase' => 'Clase 39: Xilobium y géneros aliados'],
            ['id_clase' => 40, 'id_grupp' => 4, 'nombre_clase' => 'Clase 40: Híbridos intergenéricos de la subtribu Maxillariinae'],
            ['id_clase' => 41, 'id_grupp' => 4, 'nombre_clase' => 'Clase 41: Ackermania, Bifrenaria y géneros aliados'],
            ['id_clase' => 42, 'id_grupp' => 4, 'nombre_clase' => 'Clase 42: Cyrtopodium y géneros aliados'],
            ['id_clase' => 43, 'id_grupp' => 4, 'nombre_clase' => 'Clase 43: Catasetum, Clowesia y géneros aliados'],
            ['id_clase' => 44, 'id_grupp' => 4, 'nombre_clase' => 'Clase 44: Acineta, Coryanthes y géneros aliados'],
            ['id_clase' => 45, 'id_grupp' => 5, 'nombre_clase' => 'Clase 45: Trichocentrum, Conhiella, Lophiaris, etc.'],
            ['id_clase' => 46, 'id_grupp' => 5, 'nombre_clase' => 'Clase 46: Oncidium hoja delgada'],
            ['id_clase' => 47, 'id_grupp' => 5, 'nombre_clase' => 'Clase 47: Otros géneros: Tolumnia, Cyrtochilum, etc.'],
            ['id_clase' => 48, 'id_grupp' => 5, 'nombre_clase' => 'Clase 48: Rhynchostele especie'],
            ['id_clase' => 49, 'id_grupp' => 5, 'nombre_clase' => 'Clase 49: Rossioglossum especie'],
            ['id_clase' => 50, 'id_grupp' => 5, 'nombre_clase' => 'Clase 50: Cuitlauzina especie'],
            ['id_clase' => 51, 'id_grupp' => 5, 'nombre_clase' => 'Clase 51: Brassia especie'],
            ['id_clase' => 52, 'id_grupp' => 5, 'nombre_clase' => 'Clase 52: Miltonia y Miltoniopsis especie'],
            ['id_clase' => 53, 'id_grupp' => 5, 'nombre_clase' => 'Clase 53: Trichopilia'],
            ['id_clase' => 54, 'id_grupp' => 5, 'nombre_clase' => 'Clase 54: Otros géneros aliados a Oncidium'],
            ['id_clase' => 55, 'id_grupp' => 5, 'nombre_clase' => 'Clase 55: Híbrido tipo Brassia, Odontoglossum'],
            ['id_clase' => 56, 'id_grupp' => 5, 'nombre_clase' => 'Clase 56: Otros híbridos no mencionados'],
            ['id_clase' => 57, 'id_grupp' => 6, 'nombre_clase' => 'Clase 57: Phragmipedium, Cypripedium y géneros aliados'],
            ['id_clase' => 58, 'id_grupp' => 6, 'nombre_clase' => 'Clase 58: Phragmipedium híbrido'],
            ['id_clase' => 59, 'id_grupp' => 6, 'nombre_clase' => 'Clase 59: Paphiopedilum especie'],
            ['id_clase' => 60, 'id_grupp' => 6, 'nombre_clase' => 'Clase 60: Paphiopedilum híbrido unifloral'],
            ['id_clase' => 61, 'id_grupp' => 6, 'nombre_clase' => 'Clase 61: Paphiopedilum híbrido multifloral'],
            ['id_clase' => 62, 'id_grupp' => 6, 'nombre_clase' => 'Clase 62: Paphiopedilum híbrido tipo Complex'],
            ['id_clase' => 63, 'id_grupp' => 7, 'nombre_clase' => 'Clase 63: Ascocentrum y Ascocenda especie e híbrido'],
            ['id_clase' => 64, 'id_grupp' => 7, 'nombre_clase' => 'Clase 64: Vanda especie'],
            ['id_clase' => 65, 'id_grupp' => 7, 'nombre_clase' => 'Clase 65: Vanda híbrido'],
            ['id_clase' => 66, 'id_grupp' => 7, 'nombre_clase' => 'Clase 66: Angraecum'],
            ['id_clase' => 67, 'id_grupp' => 7, 'nombre_clase' => 'Clase 67: Vandáceas especies o híbridos no mencionados anteriormente'],
            ['id_clase' => 68, 'id_grupp' => 7, 'nombre_clase' => 'Clase 68: Phalaenopsis especie'],
            ['id_clase' => 69, 'id_grupp' => 7, 'nombre_clase' => 'Clase 69: Phalaenopsis blancas híbrido'],
            ['id_clase' => 70, 'id_grupp' => 7, 'nombre_clase' => 'Clase 70: Phalaenopsis otros colores híbridos'],
            ['id_clase' => 71, 'id_grupp' => 7, 'nombre_clase' => 'Clase 71: Phalaenopsis tipo miniatura'],
            ['id_clase' => 72, 'id_grupp' => 8, 'nombre_clase' => 'Clase 72: Cymbidium y Cymbidella especie'],
            ['id_clase' => 73, 'id_grupp' => 8, 'nombre_clase' => 'Clase 73: Cymbidium híbrido'],
            ['id_clase' => 74, 'id_grupp' => 8, 'nombre_clase' => 'Clase 74: Grammathophyllum especie y híbrido'],
            ['id_clase' => 75, 'id_grupp' => 8, 'nombre_clase' => 'Clase 75: Dendrobium y Oxystophyllum especie'],
            ['id_clase' => 76, 'id_grupp' => 8, 'nombre_clase' => 'Clase 76: Dendrobium miniatura especie'],
            ['id_clase' => 77, 'id_grupp' => 8, 'nombre_clase' => 'Clase 77: Dendrobium miniatura híbrido'],
            ['id_clase' => 78, 'id_grupp' => 8, 'nombre_clase' => 'Clase 78: Dendrobium tipo nobile, phalaenopsis, antílope híbrido'],
            ['id_clase' => 79, 'id_grupp' => 8, 'nombre_clase' => 'Clase 79: Bulbophyllum especie e híbrido'],
            ['id_clase' => 80, 'id_grupp' => 8, 'nombre_clase' => 'Clase 80: Dendrochilum especie e híbrido'],
            ['id_clase' => 81, 'id_grupp' => 8, 'nombre_clase' => 'Clase 81: Coelogyne y géneros aliados especie e híbrido'],
            ['id_clase' => 82, 'id_grupp' => 8, 'nombre_clase' => 'Clase 82: Calanthe, Ludisia y géneros similares'],
            ['id_clase' => 83, 'id_grupp' => 9, 'nombre_clase' => 'Clase 83: Pleurothallis pansamalae y similares'],
            ['id_clase' => 84, 'id_grupp' => 9, 'nombre_clase' => 'Clase 84: Pleurothallis cardiothallis y similares'],
            ['id_clase' => 85, 'id_grupp' => 9, 'nombre_clase' => 'Clase 85: Acianthera'],
            ['id_clase' => 86, 'id_grupp' => 9, 'nombre_clase' => 'Clase 86: Kraenziniella, Myoxanthus y similares'],
            ['id_clase' => 87, 'id_grupp' => 9, 'nombre_clase' => 'Clase 87: Stelis (sensu latu)'],
            ['id_clase' => 88, 'id_grupp' => 9, 'nombre_clase' => 'Clase 88: Stelis (sensu stricto)'],
            ['id_clase' => 89, 'id_grupp' => 9, 'nombre_clase' => 'Clase 89: Otras Pleurothallidinae con inflorescencia más larga que la hoja'],
            ['id_clase' => 90, 'id_grupp' => 9, 'nombre_clase' => 'Clase 90: Platystele'],
            ['id_clase' => 91, 'id_grupp' => 9, 'nombre_clase' => 'Clase 91: Lankesteriana'],
            ['id_clase' => 92, 'id_grupp' => 9, 'nombre_clase' => 'Clase 92: Lephantes tipo guatemalensis'],
            ['id_clase' => 93, 'id_grupp' => 9, 'nombre_clase' => 'Clase 93: Lephantes tipo stenophylla'],
            ['id_clase' => 94, 'id_grupp' => 9, 'nombre_clase' => 'Clase 94: Lephantes tipo scopula'],
            ['id_clase' => 95, 'id_grupp' => 9, 'nombre_clase' => 'Clase 95: Lepanthopsis'],
            ['id_clase' => 96, 'id_grupp' => 9, 'nombre_clase' => 'Clase 96: Trichosalpinx'],
            ['id_clase' => 97, 'id_grupp' => 9, 'nombre_clase' => 'Clase 97: Specklinia'],
            ['id_clase' => 98, 'id_grupp' => 9, 'nombre_clase' => 'Clase 98: Otras Pleurothallidinae pequeñas'],
            ['id_clase' => 99, 'id_grupp' => 9, 'nombre_clase' => 'Clase 99: Restrepia especie e híbrido'],
            ['id_clase' => 100, 'id_grupp' => 9, 'nombre_clase' => 'Clase 100: Masdevallia de México y C.A. especie'],
            ['id_clase' => 101, 'id_grupp' => 9, 'nombre_clase' => 'Clase 101: Masdevallia tipo sudamericanas especie'],
            ['id_clase' => 102, 'id_grupp' => 9, 'nombre_clase' => 'Clase 102: Masdevallias híbrido'],
            ['id_clase' => 103, 'id_grupp' => 9, 'nombre_clase' => 'Clase 103: Draculas especies e híbrido'],
            ['id_clase' => 104, 'id_grupp' => 10, 'nombre_clase' => 'Clase 104: Dichaea tipo rastrera y similares'],
            ['id_clase' => 105, 'id_grupp' => 10, 'nombre_clase' => 'Clase 105: Campylocentrum y otros géneros pequeños'],
            ['id_clase' => 106, 'id_grupp' => 11, 'nombre_clase' => 'Clase 106: Cranichideae y géneros aliados'],
            ['id_clase' => 107, 'id_grupp' => 11, 'nombre_clase' => 'Clase 107: Habenaria, Triphora y géneros aliados'],
            ['id_clase' => 108, 'id_grupp' => 12, 'nombre_clase' => 'Clase 108: Bouquets de novia'],
            ['id_clase' => 109, 'id_grupp' => 12, 'nombre_clase' => 'Clase 109: Arreglos tradicionales'],
            ['id_clase' => 110, 'id_grupp' => 12, 'nombre_clase' => 'Clase 110: Arreglos modernos/ Línea abstracta'],
            ['id_clase' => 111, 'id_grupp' => 12, 'nombre_clase' => 'Clase 111: Flor cortada'],
            ['id_clase' => 112, 'id_grupp' => 13, 'nombre_clase' => 'Clase 112: Tema educacional sobre orquídeas'],
            ['id_clase' => 113, 'id_grupp' => 13, 'nombre_clase' => 'Clase 113: Tema educacional sobre medio ambiente'],
            ['id_clase' => 114, 'id_grupp' => 14, 'nombre_clase' => 'Otros'],
        ]);
    }
}