<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipio;


class MunicipioSeeder   
 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Municipio::insert([
            //Departamento de Guatemala
            ['id_municipio' => 1, 'id_departamento' => 1, 'nombre_municipio' => 'Municipio de Guatemala'],
            ['id_municipio' => 2, 'id_departamento' => 1, 'nombre_municipio' => 'Santa Catarina Pinula'],
            ['id_municipio' => 3, 'id_departamento' => 1, 'nombre_municipio' => 'San José Pinula'],
            ['id_municipio' => 4, 'id_departamento' => 1, 'nombre_municipio' => 'San José del Golfo'],
            ['id_municipio' => 5, 'id_departamento' => 1, 'nombre_municipio' => 'Palencia'],
            ['id_municipio' => 6, 'id_departamento' => 1, 'nombre_municipio' => 'Chinautla'],
            ['id_municipio' => 7, 'id_departamento' => 1, 'nombre_municipio' => 'San Pedro Ayampuc'],
            ['id_municipio' => 8, 'id_departamento' => 1, 'nombre_municipio' => 'Mixco'],
            ['id_municipio' => 9, 'id_departamento' => 1, 'nombre_municipio' => 'San Pedro Sacatepéquez'],
            ['id_municipio' => 10, 'id_departamento' => 1, 'nombre_municipio' => 'San Juan Sacatepéquez'],
            ['id_municipio' => 11, 'id_departamento' => 1, 'nombre_municipio' => 'San Raimundo'],
            ['id_municipio' => 12, 'id_departamento' => 1, 'nombre_municipio' => 'Chuarrancho'],
            ['id_municipio' => 13, 'id_departamento' => 1, 'nombre_municipio' => 'Fraijanes'],
            ['id_municipio' => 14, 'id_departamento' => 1, 'nombre_municipio' => 'Amatitlán'],
            ['id_municipio' => 15, 'id_departamento' => 1, 'nombre_municipio' => 'Villa Nueva'],
            ['id_municipio' => 16, 'id_departamento' => 1, 'nombre_municipio' => 'Villa Canales'],
            ['id_municipio' => 17, 'id_departamento' => 1, 'nombre_municipio' => 'Petapa'],

            // Departamento de El Progreso
            ['id_municipio' => 18, 'id_departamento' => 2, 'nombre_municipio' => 'Guastatoya'],
            ['id_municipio' => 19, 'id_departamento' => 2, 'nombre_municipio' => 'Morazán'],
            ['id_municipio' => 20, 'id_departamento' => 2, 'nombre_municipio' => 'San Agustín Acasaguastlán'],
            ['id_municipio' => 21, 'id_departamento' => 2, 'nombre_municipio' => 'San Cristóbal Acasaguastlán'],
            ['id_municipio' => 22, 'id_departamento' => 2, 'nombre_municipio' => 'El Jícaro'],
            ['id_municipio' => 23, 'id_departamento' => 2, 'nombre_municipio' => 'Sansare'],
            ['id_municipio' => 24, 'id_departamento' => 2, 'nombre_municipio' => 'Sanarate'],
            ['id_municipio' => 25, 'id_departamento' => 2, 'nombre_municipio' => 'San Antonio La Paz'],

            // Departamento de Sacatepéquez
            ['id_municipio' => 26, 'id_departamento' => 3, 'nombre_municipio' => 'Antigua Guatemala'],
            ['id_municipio' => 27, 'id_departamento' => 3, 'nombre_municipio' => 'Jocotenango'],
            ['id_municipio' => 28, 'id_departamento' => 3, 'nombre_municipio' => 'Pastores'],
            ['id_municipio' => 29, 'id_departamento' => 3, 'nombre_municipio' => 'Sumpango'],
            ['id_municipio' => 30, 'id_departamento' => 3, 'nombre_municipio' => 'Santo Domingo Xenacoj'],
            ['id_municipio' => 31, 'id_departamento' => 3, 'nombre_municipio' => 'Santiago Sacatepéquez'],
            ['id_municipio' => 32, 'id_departamento' => 3, 'nombre_municipio' => 'San Bartolomé Milpas Altas'],
            ['id_municipio' => 33, 'id_departamento' => 3, 'nombre_municipio' => 'San Lucas Sacatepéquez'],
            ['id_municipio' => 34, 'id_departamento' => 3, 'nombre_municipio' => 'Santa Lucía Milpas Altas'],
            ['id_municipio' => 35, 'id_departamento' => 3, 'nombre_municipio' => 'Magdalena Milpas Altas'],
            ['id_municipio' => 36, 'id_departamento' => 3, 'nombre_municipio' => 'Santa María de Jesús'],
            ['id_municipio' => 37, 'id_departamento' => 3, 'nombre_municipio' => 'Ciudad Vieja'],
            ['id_municipio' => 38, 'id_departamento' => 3, 'nombre_municipio' => 'San Miguel Dueñas'],
            ['id_municipio' => 39, 'id_departamento' => 3, 'nombre_municipio' => 'Alotenango'],
            ['id_municipio' => 40, 'id_departamento' => 3, 'nombre_municipio' => 'San Antonio Aguas Calientes'],
            ['id_municipio' => 41, 'id_departamento' => 3, 'nombre_municipio' => 'Santa Catalina Barahona'],

            // Departamento de Chimaltenango
            ['id_municipio' => 42, 'id_departamento' => 4, 'nombre_municipio' => 'Chimaltenango'],
            ['id_municipio' => 43, 'id_departamento' => 4, 'nombre_municipio' => 'San José Poaquil'],
            ['id_municipio' => 44, 'id_departamento' => 4, 'nombre_municipio' => 'San Martín Jilotepeque'],
            ['id_municipio' => 45, 'id_departamento' => 4, 'nombre_municipio' => 'Comalapa'],
            ['id_municipio' => 46, 'id_departamento' => 4, 'nombre_municipio' => 'Santa Apolonia'],
            ['id_municipio' => 47, 'id_departamento' => 4, 'nombre_municipio' => 'Tecpán Guatemala'],
            ['id_municipio' => 48, 'id_departamento' => 4, 'nombre_municipio' => 'Patzún'],
            ['id_municipio' => 49, 'id_departamento' => 4, 'nombre_municipio' => 'Pochuta'],
            ['id_municipio' => 50, 'id_departamento' => 4, 'nombre_municipio' => 'Patzicía'],
            ['id_municipio' => 51, 'id_departamento' => 4, 'nombre_municipio' => 'Santa Cruz Balanyá'],
            ['id_municipio' => 52, 'id_departamento' => 4, 'nombre_municipio' => 'Acatenango'],
            ['id_municipio' => 53, 'id_departamento' => 4, 'nombre_municipio' => 'Yepocapa'],
            ['id_municipio' => 54, 'id_departamento' => 4, 'nombre_municipio' => 'San Andrés Itzapa'],
            ['id_municipio' => 55, 'id_departamento' => 4, 'nombre_municipio' => 'Parramos'],
            ['id_municipio' => 56, 'id_departamento' => 4, 'nombre_municipio' => 'Zaragoza'],
            ['id_municipio' => 57, 'id_departamento' => 4, 'nombre_municipio' => 'El Tejar'],

            // Departamento de Escuintla
            ['id_municipio' => 58, 'id_departamento' => 5, 'nombre_municipio' => 'Escuintla'],
            ['id_municipio' => 59, 'id_departamento' => 5, 'nombre_municipio' => 'Santa Lucía Cotzumalguapa'],
            ['id_municipio' => 60, 'id_departamento' => 5, 'nombre_municipio' => 'La Democracia'],
            ['id_municipio' => 61, 'id_departamento' => 5, 'nombre_municipio' => 'Siquinalá'],
            ['id_municipio' => 62, 'id_departamento' => 5, 'nombre_municipio' => 'Masagua'],
            ['id_municipio' => 63, 'id_departamento' => 5, 'nombre_municipio' => 'Tiquisate'],
            ['id_municipio' => 64, 'id_departamento' => 5, 'nombre_municipio' => 'La Gomera'],
            ['id_municipio' => 65, 'id_departamento' => 5, 'nombre_municipio' => 'Guanagazapa'],
            ['id_municipio' => 66, 'id_departamento' => 5, 'nombre_municipio' => 'San José'],
            ['id_municipio' => 67, 'id_departamento' => 5, 'nombre_municipio' => 'Iztapa'],
            ['id_municipio' => 68, 'id_departamento' => 5, 'nombre_municipio' => 'Palín'],
            ['id_municipio' => 69, 'id_departamento' => 5, 'nombre_municipio' => 'San Vicente Pacaya'],
            ['id_municipio' => 70, 'id_departamento' => 5, 'nombre_municipio' => 'Nueva Concepción'],

            // Departamento de Santa Rosa
            ['id_municipio' => 71, 'id_departamento' => 6, 'nombre_municipio' => 'Cuilapa'],
            ['id_municipio' => 72, 'id_departamento' => 6, 'nombre_municipio' => 'Barberena'],
            ['id_municipio' => 73, 'id_departamento' => 6, 'nombre_municipio' => 'Santa Rosa de Lima'],
            ['id_municipio' => 74, 'id_departamento' => 6, 'nombre_municipio' => 'Casillas'],
            ['id_municipio' => 75, 'id_departamento' => 6, 'nombre_municipio' => 'San Rafael Las Flores'],
            ['id_municipio' => 76, 'id_departamento' => 6, 'nombre_municipio' => 'Oratorio'],
            ['id_municipio' => 77, 'id_departamento' => 6, 'nombre_municipio' => 'San Juan Tecuaco'],
            ['id_municipio' => 78, 'id_departamento' => 6, 'nombre_municipio' => 'Chiquimulilla'],
            ['id_municipio' => 79, 'id_departamento' => 6, 'nombre_municipio' => 'Taxisco'],
            ['id_municipio' => 80, 'id_departamento' => 6, 'nombre_municipio' => 'Santa María Ixhuatán'],
            ['id_municipio' => 81, 'id_departamento' => 6, 'nombre_municipio' => 'Guazacapán'],
            ['id_municipio' => 82, 'id_departamento' => 6, 'nombre_municipio' => 'Santa Cruz Naranjo'],
            ['id_municipio' => 83, 'id_departamento' => 6, 'nombre_municipio' => 'Pueblo Nuevo Viñas'],
            ['id_municipio' => 84, 'id_departamento' => 6, 'nombre_municipio' => 'Nueva Santa Rosa'],

            //Solola
            ['id_municipio' => 85, 'id_departamento' => 7, 'nombre_municipio' => 'Sololá'],
            ['id_municipio' => 86, 'id_departamento' => 7, 'nombre_municipio' => 'San José Chacayá'],
            ['id_municipio' => 87, 'id_departamento' => 7, 'nombre_municipio' => 'Santa María Visitación'],
            ['id_municipio' => 88, 'id_departamento' => 7, 'nombre_municipio' => 'Santa Lucía Utatlán'],
            ['id_municipio' => 89, 'id_departamento' => 7, 'nombre_municipio' => 'Nahualá'],
            ['id_municipio' => 90, 'id_departamento' => 7, 'nombre_municipio' => 'Santa Catarina Ixtahuacan'],
            ['id_municipio' => 91, 'id_departamento' => 7, 'nombre_municipio' => 'Santa Clara La Laguna'],
            ['id_municipio' => 92, 'id_departamento' => 7, 'nombre_municipio' => 'Concepción'],
            ['id_municipio' => 93, 'id_departamento' => 7, 'nombre_municipio' => 'San Andrés Semetabaj'],
            ['id_municipio' => 94, 'id_departamento' => 7, 'nombre_municipio' => 'Panajachel'],
            ['id_municipio' => 95, 'id_departamento' => 7, 'nombre_municipio' => 'Santa Catarina Palopó'],
            ['id_municipio' => 96, 'id_departamento' => 7, 'nombre_municipio' => 'San Antonio Palopó'],
            ['id_municipio' => 97, 'id_departamento' => 7, 'nombre_municipio' => 'San Lucas Tolimán'],
            ['id_municipio' => 98, 'id_departamento' => 7, 'nombre_municipio' => 'Santa Cruz La Laguna'],
            ['id_municipio' => 99, 'id_departamento' => 7, 'nombre_municipio' => 'San Pablo La Laguna'],
            ['id_municipio' => 100, 'id_departamento' => 7, 'nombre_municipio' => 'San Marcos La Laguna'],
            ['id_municipio' => 101, 'id_departamento' => 7, 'nombre_municipio' => 'San Juan La Laguna'],
            ['id_municipio' => 102, 'id_departamento' => 7, 'nombre_municipio' => 'San Pedro La Laguna'],
            ['id_municipio' => 103, 'id_departamento' => 7, 'nombre_municipio' => 'Santiago Atitlán'],

            //Totonicapan
            ['id_municipio' => 104, 'id_departamento' => 8, 'nombre_municipio' => 'Totonicapán'],
            ['id_municipio' => 105, 'id_departamento' => 8, 'nombre_municipio' => 'San Cristóbal Totonicapán'],
            ['id_municipio' => 106, 'id_departamento' => 8, 'nombre_municipio' => 'San Francisco El Alto'],
            ['id_municipio' => 107, 'id_departamento' => 8, 'nombre_municipio' => 'San Andrés Xecul'],
            ['id_municipio' => 108, 'id_departamento' => 8, 'nombre_municipio' => 'Momostenango'],
            ['id_municipio' => 109, 'id_departamento' => 8, 'nombre_municipio' => 'Santa María Chiquimula'],
            ['id_municipio' => 110, 'id_departamento' => 8, 'nombre_municipio' => 'Santa Lucía La Reforma'],
            ['id_municipio' => 111, 'id_departamento' => 8, 'nombre_municipio' => 'San Bartolo'],

            //Quetzaltenango
            ['id_municipio' => 112, 'id_departamento' => 9, 'nombre_municipio' => 'Quetzaltenango'],
            ['id_municipio' => 113, 'id_departamento' => 9, 'nombre_municipio' => 'Salcajá'],
            ['id_municipio' => 114, 'id_departamento' => 9, 'nombre_municipio' => 'Olintepeque'],
            ['id_municipio' => 115, 'id_departamento' => 9, 'nombre_municipio' => 'San Carlos Sija'],
            ['id_municipio' => 116, 'id_departamento' => 9, 'nombre_municipio' => 'Sibilia'],
            ['id_municipio' => 117, 'id_departamento' => 9, 'nombre_municipio' => 'Cabricán'],
            ['id_municipio' => 118, 'id_departamento' => 9, 'nombre_municipio' => 'Cajolá'],
            ['id_municipio' => 119, 'id_departamento' => 9, 'nombre_municipio' => 'San Miguel Sigüilá'],
            ['id_municipio' => 120, 'id_departamento' => 9, 'nombre_municipio' => 'Ostuncalco'],
            ['id_municipio' => 121, 'id_departamento' => 9, 'nombre_municipio' => 'San Mateo'],
            ['id_municipio' => 122, 'id_departamento' => 9, 'nombre_municipio' => 'Concepción Chiquirichapa'],
            ['id_municipio' => 123, 'id_departamento' => 9, 'nombre_municipio' => 'San Martín Sacatepéquez'],
            ['id_municipio' => 124, 'id_departamento' => 9, 'nombre_municipio' => 'Almolonga'],
            ['id_municipio' => 125, 'id_departamento' => 9, 'nombre_municipio' => 'Cantel'],
            ['id_municipio' => 126, 'id_departamento' => 9, 'nombre_municipio' => 'Huitán'],
            ['id_municipio' => 127, 'id_departamento' => 9, 'nombre_municipio' => 'Zunil'],
            ['id_municipio' => 128, 'id_departamento' => 9, 'nombre_municipio' => 'Colomba'],
            ['id_municipio' => 129, 'id_departamento' => 9, 'nombre_municipio' => 'San Francisco La Unión'],
            ['id_municipio' => 130, 'id_departamento' => 9, 'nombre_municipio' => 'El Palmar'],
            ['id_municipio' => 131, 'id_departamento' => 9, 'nombre_municipio' => 'Coatepeque'],
            ['id_municipio' => 132, 'id_departamento' => 9, 'nombre_municipio' => 'Génova'],
            ['id_municipio' => 133, 'id_departamento' => 9, 'nombre_municipio' => 'Flores Costa Cuca'],
            ['id_municipio' => 134, 'id_departamento' => 9, 'nombre_municipio' => 'La Esperanza'],
            ['id_municipio' => 135, 'id_departamento' => 9, 'nombre_municipio' => 'Palestina de los Altos'],

            //Suchitepéquez 
            ['id_municipio' => 136, 'id_departamento' => 10, 'nombre_municipio' => 'Mazatenango'],
            ['id_municipio' => 137, 'id_departamento' => 10, 'nombre_municipio' => 'Cuyotenango'],
            ['id_municipio' => 138, 'id_departamento' => 10, 'nombre_municipio' => 'San Francisco Zapotitlán'],
            ['id_municipio' => 139, 'id_departamento' => 10, 'nombre_municipio' => 'San Bernardino'],
            ['id_municipio' => 140, 'id_departamento' => 10, 'nombre_municipio' => 'San José El Idolo'],
            ['id_municipio' => 141, 'id_departamento' => 10, 'nombre_municipio' => 'Santo Domingo Suchitepequez'],
            ['id_municipio' => 142, 'id_departamento' => 10, 'nombre_municipio' => 'San Lorenzo'],
            ['id_municipio' => 143, 'id_departamento' => 10, 'nombre_municipio' => 'Samayac'],
            ['id_municipio' => 144, 'id_departamento' => 10, 'nombre_municipio' => 'San Pablo Jocopilas'],
            ['id_municipio' => 145, 'id_departamento' => 10, 'nombre_municipio' => 'San Antonio Suchitepequez'],
            ['id_municipio' => 146, 'id_departamento' => 10, 'nombre_municipio' => 'San Miguel Panan'],
            ['id_municipio' => 147, 'id_departamento' => 10, 'nombre_municipio' => 'San Gabriel'],
            ['id_municipio' => 148, 'id_departamento' => 10, 'nombre_municipio' => 'Chicacao'],
            ['id_municipio' => 149, 'id_departamento' => 10, 'nombre_municipio' => 'Patulul'],
            ['id_municipio' => 150, 'id_departamento' => 10, 'nombre_municipio' => 'Santa Barbara'],
            ['id_municipio' => 151, 'id_departamento' => 10, 'nombre_municipio' => 'San Juan Bautista'],
            ['id_municipio' => 152, 'id_departamento' => 10, 'nombre_municipio' => 'Santo Tomás La Unión'],
            ['id_municipio' => 153, 'id_departamento' => 10, 'nombre_municipio' => 'Zunilito'],
            ['id_municipio' => 154, 'id_departamento' => 10, 'nombre_municipio' => 'Pueblo Nuevo'],
            ['id_municipio' => 155, 'id_departamento' => 10, 'nombre_municipio' => 'Río Bravo'],

            // Municipios de Retalhuleu 
            ['id_municipio' => 156, 'id_departamento' => 11, 'nombre_municipio' => 'Retalhuleu'],
            ['id_municipio' => 157, 'id_departamento' => 11, 'nombre_municipio' => 'San Sebastián'],
            ['id_municipio' => 158, 'id_departamento' => 11, 'nombre_municipio' => 'Santa Cruz Muluá'],
            ['id_municipio' => 159, 'id_departamento' => 11, 'nombre_municipio' => 'San Martín Zapotitlán'],
            ['id_municipio' => 160, 'id_departamento' => 11, 'nombre_municipio' => 'San Felipe'],
            ['id_municipio' => 161, 'id_departamento' => 11, 'nombre_municipio' => 'San Andrés Villa Seca'],
            ['id_municipio' => 162, 'id_departamento' => 11, 'nombre_municipio' => 'Champerico'],
            ['id_municipio' => 163, 'id_departamento' => 11, 'nombre_municipio' => 'Nuevo San Carlos'],
            ['id_municipio' => 164, 'id_departamento' => 11, 'nombre_municipio' => 'El Asintal'],

            //San marcos
            ['id_municipio' => 165, 'id_departamento' => 12, 'nombre_municipio' => 'San Marcos'],
            ['id_municipio' => 166, 'id_departamento' => 12, 'nombre_municipio' => 'San Pedro Sacatepéquez'],
            ['id_municipio' => 167, 'id_departamento' => 12, 'nombre_municipio' => 'San Antonio Sacatepéquez'],
            ['id_municipio' => 168, 'id_departamento' => 12, 'nombre_municipio' => 'Comitancillo'],
            ['id_municipio' => 169, 'id_departamento' => 12, 'nombre_municipio' => 'San Miguel Ixtahuacán'],
            ['id_municipio' => 170, 'id_departamento' => 12, 'nombre_municipio' => 'Concepción Tutuapa'],
            ['id_municipio' => 171, 'id_departamento' => 12, 'nombre_municipio' => 'Tacaná'],
            ['id_municipio' => 172, 'id_departamento' => 12, 'nombre_municipio' => 'Sibinal'],
            ['id_municipio' => 173, 'id_departamento' => 12, 'nombre_municipio' => 'Tajumulco'],
            ['id_municipio' => 174, 'id_departamento' => 12, 'nombre_municipio' => 'Tejutla'],
            ['id_municipio' => 175, 'id_departamento' => 12, 'nombre_municipio' => 'San Rafael Pie De La Cuesta'],
            ['id_municipio' => 176, 'id_departamento' => 12, 'nombre_municipio' => 'Nuevo Progreso'],
            ['id_municipio' => 177, 'id_departamento' => 12, 'nombre_municipio' => 'El Tumbador'],
            ['id_municipio' => 178, 'id_departamento' => 12, 'nombre_municipio' => 'El Rodeo'],
            ['id_municipio' => 179, 'id_departamento' => 12, 'nombre_municipio' => 'Malacatán'],
            ['id_municipio' => 180, 'id_departamento' => 12, 'nombre_municipio' => 'Catarina'],
            ['id_municipio' => 181, 'id_departamento' => 12, 'nombre_municipio' => 'Ayutla'],
            ['id_municipio' => 182, 'id_departamento' => 12, 'nombre_municipio' => 'Ocós'],
            ['id_municipio' => 183, 'id_departamento' => 12, 'nombre_municipio' => 'San Pablo'],
            ['id_municipio' => 184, 'id_departamento' => 12, 'nombre_municipio' => 'El Quetzal'],
            ['id_municipio' => 185, 'id_departamento' => 12, 'nombre_municipio' => 'La Reforma'],
            ['id_municipio' => 186, 'id_departamento' => 12, 'nombre_municipio' => 'Pajapita'],
            ['id_municipio' => 187, 'id_departamento' => 12, 'nombre_municipio' => 'Ixchiguán'],
            ['id_municipio' => 188, 'id_departamento' => 12, 'nombre_municipio' => 'San José Ojetenam'],
            ['id_municipio' => 189, 'id_departamento' => 12, 'nombre_municipio' => 'San Cristóbal Cucho'],
            ['id_municipio' => 190, 'id_departamento' => 12, 'nombre_municipio' => 'Sipacapa'],
            ['id_municipio' => 191, 'id_departamento' => 12, 'nombre_municipio' => 'Esquipulas Palo Gordo'],
            ['id_municipio' => 192, 'id_departamento' => 12, 'nombre_municipio' => 'Río Blanco'],
            ['id_municipio' => 193, 'id_departamento' => 12, 'nombre_municipio' => 'San Lorenzo'],

            //Huehuetenango
            ['id_municipio' => 194, 'id_departamento' => 13, 'nombre_municipio' => 'Huehuetenango'],
            ['id_municipio' => 195, 'id_departamento' => 13, 'nombre_municipio' => 'Chiantla'],
            ['id_municipio' => 196, 'id_departamento' => 13, 'nombre_municipio' => 'Malacatancito'],
            ['id_municipio' => 197, 'id_departamento' => 13, 'nombre_municipio' => 'Cuilco'],
            ['id_municipio' => 198, 'id_departamento' => 13, 'nombre_municipio' => 'Nentón'],
            ['id_municipio' => 199, 'id_departamento' => 13, 'nombre_municipio' => 'San Pedro Necta'],
            ['id_municipio' => 200, 'id_departamento' => 13, 'nombre_municipio' => 'Jacaltenango'],
            ['id_municipio' => 201, 'id_departamento' => 13, 'nombre_municipio' => 'Soloma'],
            ['id_municipio' => 202, 'id_departamento' => 13, 'nombre_municipio' => 'Ixtahuacán'],
            ['id_municipio' => 203, 'id_departamento' => 13, 'nombre_municipio' => 'Santa Bárbara'],
            ['id_municipio' => 204, 'id_departamento' => 13, 'nombre_municipio' => 'La Libertad'],
            ['id_municipio' => 205, 'id_departamento' => 13, 'nombre_municipio' => 'La Democracia'],
            ['id_municipio' => 206, 'id_departamento' => 13, 'nombre_municipio' => 'San Miguel Acatán'],
            ['id_municipio' => 207, 'id_departamento' => 13, 'nombre_municipio' => 'San Rafael La Independencia'],
            ['id_municipio' => 208, 'id_departamento' => 13, 'nombre_municipio' => 'Todos Santos Cuchumatánes'],
            ['id_municipio' => 209, 'id_departamento' => 13, 'nombre_municipio' => 'San Juan Atitán'],
            ['id_municipio' => 210, 'id_departamento' => 13, 'nombre_municipio' => 'Santa Eulalia'],
            ['id_municipio' => 211, 'id_departamento' => 13, 'nombre_municipio' => 'San Mateo Ixtatán'],
            ['id_municipio' => 212, 'id_departamento' => 13, 'nombre_municipio' => 'Colotenango'],
            ['id_municipio' => 213, 'id_departamento' => 13, 'nombre_municipio' => 'San Sebastián Huehuetenango'],
            ['id_municipio' => 214, 'id_departamento' => 13, 'nombre_municipio' => 'Tectitán'],
            ['id_municipio' => 215, 'id_departamento' => 13, 'nombre_municipio' => 'Concepción Huista'],
            ['id_municipio' => 216, 'id_departamento' => 13, 'nombre_municipio' => 'San Juan Ixcoy'],
            ['id_municipio' => 217, 'id_departamento' => 13, 'nombre_municipio' => 'San Antonio Huista'],
            ['id_municipio' => 218, 'id_departamento' => 13, 'nombre_municipio' => 'San Sebastián Coatán'],
            ['id_municipio' => 219, 'id_departamento' => 13, 'nombre_municipio' => 'Barillas'],
            ['id_municipio' => 220, 'id_departamento' => 13, 'nombre_municipio' => 'Aguacatán'],
            ['id_municipio' => 221, 'id_departamento' => 13, 'nombre_municipio' => 'San Rafael Petzal'],
            ['id_municipio' => 222, 'id_departamento' => 13, 'nombre_municipio' => 'San Gaspar Ixchil'],
            ['id_municipio' => 223, 'id_departamento' => 13, 'nombre_municipio' => 'Santiago Chimaltenango'],
            ['id_municipio' => 224, 'id_departamento' => 13, 'nombre_municipio' => 'Santa Ana Huista'],

            // Municipios de El Quiché 
            ['id_municipio' => 225, 'id_departamento' => 14, 'nombre_municipio' => 'Santa Cruz del Quiché'],
            ['id_municipio' => 226, 'id_departamento' => 14, 'nombre_municipio' => 'Chiché'],
            ['id_municipio' => 227, 'id_departamento' => 14, 'nombre_municipio' => 'Chinique'],
            ['id_municipio' => 228, 'id_departamento' => 14, 'nombre_municipio' => 'Zacualpa'],
            ['id_municipio' => 229, 'id_departamento' => 14, 'nombre_municipio' => 'Chajul'],
            ['id_municipio' => 230, 'id_departamento' => 14, 'nombre_municipio' => 'Chichicastenango'],
            ['id_municipio' => 231, 'id_departamento' => 14, 'nombre_municipio' => 'Patzité'],
            ['id_municipio' => 232, 'id_departamento' => 14, 'nombre_municipio' => 'San Antonio Ilotenango'],
            ['id_municipio' => 233, 'id_departamento' => 14, 'nombre_municipio' => 'San Pedro Jocopilas'],
            ['id_municipio' => 234, 'id_departamento' => 14, 'nombre_municipio' => 'Cunén'],
            ['id_municipio' => 235, 'id_departamento' => 14, 'nombre_municipio' => 'San Juan Cotzal'],
            ['id_municipio' => 236, 'id_departamento' => 14, 'nombre_municipio' => 'Joyabaj'],
            ['id_municipio' => 237, 'id_departamento' => 14, 'nombre_municipio' => 'Nebaj'],
            ['id_municipio' => 238, 'id_departamento' => 14, 'nombre_municipio' => 'San Andrés Sajcabajá'],
            ['id_municipio' => 239, 'id_departamento' => 14, 'nombre_municipio' => 'Uspantán'],
            ['id_municipio' => 240, 'id_departamento' => 14, 'nombre_municipio' => 'Sacapulas'],
            ['id_municipio' => 241, 'id_departamento' => 14, 'nombre_municipio' => 'San Bartolomé Jocotenango'],
            ['id_municipio' => 242, 'id_departamento' => 14, 'nombre_municipio' => 'Canillá'],
            ['id_municipio' => 243, 'id_departamento' => 14, 'nombre_municipio' => 'Chicamán'],
            ['id_municipio' => 244, 'id_departamento' => 14, 'nombre_municipio' => 'Ixcán'],
            ['id_municipio' => 245, 'id_departamento' => 14, 'nombre_municipio' => 'Pachalum'],

            // Municipios de Baja Verapaz 
            ['id_municipio' => 246, 'id_departamento' => 15, 'nombre_municipio' => 'Salamá'],
            ['id_municipio' => 247, 'id_departamento' => 15, 'nombre_municipio' => 'San Miguel Chicaj'],
            ['id_municipio' => 248, 'id_departamento' => 15, 'nombre_municipio' => 'Rabinal'],
            ['id_municipio' => 249, 'id_departamento' => 15, 'nombre_municipio' => 'Cubulco'],
            ['id_municipio' => 250, 'id_departamento' => 15, 'nombre_municipio' => 'Granados'],
            ['id_municipio' => 251, 'id_departamento' => 15, 'nombre_municipio' => 'El Chol'],
            ['id_municipio' => 252, 'id_departamento' => 15, 'nombre_municipio' => 'San Jerónimo'],
            ['id_municipio' => 253, 'id_departamento' => 15, 'nombre_municipio' => 'Purulhá'],

            // Municipios de Alta Verapaz 
            ['id_municipio' => 254, 'id_departamento' => 16, 'nombre_municipio' => 'Cobán'],
            ['id_municipio' => 255, 'id_departamento' => 16, 'nombre_municipio' => 'Santa Cruz Verapaz'],
            ['id_municipio' => 256, 'id_departamento' => 16, 'nombre_municipio' => 'San Cristóbal Verapaz'],
            ['id_municipio' => 257, 'id_departamento' => 16, 'nombre_municipio' => 'Tactic'],
            ['id_municipio' => 258, 'id_departamento' => 16, 'nombre_municipio' => 'Tamahú'],
            ['id_municipio' => 259, 'id_departamento' => 16, 'nombre_municipio' => 'Tucurú'],
            ['id_municipio' => 260, 'id_departamento' => 16, 'nombre_municipio' => 'Panzós'],
            ['id_municipio' => 261, 'id_departamento' => 16, 'nombre_municipio' => 'Senahú'],
            ['id_municipio' => 262, 'id_departamento' => 16, 'nombre_municipio' => 'San Pedro Carchá'],
            ['id_municipio' => 263, 'id_departamento' => 16, 'nombre_municipio' => 'San Juan Chamelco'],
            ['id_municipio' => 264, 'id_departamento' => 16, 'nombre_municipio' => 'Lanquín'],
            ['id_municipio' => 265, 'id_departamento' => 16, 'nombre_municipio' => 'Cahabón'],
            ['id_municipio' => 266, 'id_departamento' => 16, 'nombre_municipio' => 'Chisec'],
            ['id_municipio' => 267, 'id_departamento' => 16, 'nombre_municipio' => 'Chahal'],
            ['id_municipio' => 268, 'id_departamento' => 16, 'nombre_municipio' => 'Fray Bartolomé de Las Casas'],

            // Municipios de El Petén 
            ['id_municipio' => 269, 'id_departamento' => 17, 'nombre_municipio' => 'Flores'],
            ['id_municipio' => 270, 'id_departamento' => 17, 'nombre_municipio' => 'San José'],
            ['id_municipio' => 271, 'id_departamento' => 17, 'nombre_municipio' => 'San Benito'],
            ['id_municipio' => 272, 'id_departamento' => 17, 'nombre_municipio' => 'San Andrés'],
            ['id_municipio' => 273, 'id_departamento' => 17, 'nombre_municipio' => 'La Libertad'],
            ['id_municipio' => 274, 'id_departamento' => 17, 'nombre_municipio' => 'San Francisco'],
            ['id_municipio' => 275, 'id_departamento' => 17, 'nombre_municipio' => 'Santa Ana'],
            ['id_municipio' => 276, 'id_departamento' => 17, 'nombre_municipio' => 'Dolores'],
            ['id_municipio' => 277, 'id_departamento' => 17, 'nombre_municipio' => 'San Luis'],
            ['id_municipio' => 278, 'id_departamento' => 17, 'nombre_municipio' => 'Sayaxché'],
            ['id_municipio' => 279, 'id_departamento' => 17, 'nombre_municipio' => 'Melchor De Mencos'],
            ['id_municipio' => 280, 'id_departamento' => 17, 'nombre_municipio' => 'Poptún'],

            // Municipios de Izabal 
            ['id_municipio' => 281, 'id_departamento' => 18, 'nombre_municipio' => 'Puerto Barrios'],
            ['id_municipio' => 282, 'id_departamento' => 18, 'nombre_municipio' => 'Livingston'],
            ['id_municipio' => 283, 'id_departamento' => 18, 'nombre_municipio' => 'El Estor'],
            ['id_municipio' => 284, 'id_departamento' => 18, 'nombre_municipio' => 'Morales'],
            ['id_municipio' => 285, 'id_departamento' => 18, 'nombre_municipio' => 'Los Amates'],

            // Municipios de Zacapa 
            ['id_municipio' => 286, 'id_departamento' => 19, 'nombre_municipio' => 'Zacapa'],
            ['id_municipio' => 287, 'id_departamento' => 19, 'nombre_municipio' => 'Estanzuela'],
            ['id_municipio' => 288, 'id_departamento' => 19, 'nombre_municipio' => 'Río Hondo'],
            ['id_municipio' => 289, 'id_departamento' => 19, 'nombre_municipio' => 'Gualán'],
            ['id_municipio' => 290, 'id_departamento' => 19, 'nombre_municipio' => 'Teculután'],
            ['id_municipio' => 291, 'id_departamento' => 19, 'nombre_municipio' => 'Usumatlán'],
            ['id_municipio' => 292, 'id_departamento' => 19, 'nombre_municipio' => 'Cabañas'],
            ['id_municipio' => 293, 'id_departamento' => 19, 'nombre_municipio' => 'San Diego'],
            ['id_municipio' => 294, 'id_departamento' => 19, 'nombre_municipio' => 'La Unión'],
            ['id_municipio' => 295, 'id_departamento' => 19, 'nombre_municipio' => 'Huité'],

            // Municipios de Chiquimula 
            ['id_municipio' => 296, 'id_departamento' => 20, 'nombre_municipio' => 'Chiquimula'],
            ['id_municipio' => 297, 'id_departamento' => 20, 'nombre_municipio' => 'San José La Arada'],
            ['id_municipio' => 298, 'id_departamento' => 20, 'nombre_municipio' => 'San Juan Ermita'],
            ['id_municipio' => 299, 'id_departamento' => 20, 'nombre_municipio' => 'Jocotán'],
            ['id_municipio' => 300, 'id_departamento' => 20, 'nombre_municipio' => 'Camotán'],
            ['id_municipio' => 301, 'id_departamento' => 20, 'nombre_municipio' => 'Olopa'],
            ['id_municipio' => 302, 'id_departamento' => 20, 'nombre_municipio' => 'Esquipulas'],
            ['id_municipio' => 303, 'id_departamento' => 20, 'nombre_municipio' => 'Concepción Las Minas'],
            ['id_municipio' => 304, 'id_departamento' => 20, 'nombre_municipio' => 'Quezaltepeque'],
            ['id_municipio' => 305, 'id_departamento' => 20, 'nombre_municipio' => 'San Jacinto'],
            ['id_municipio' => 306, 'id_departamento' => 20, 'nombre_municipio' => 'Ipala'],

            // Municipios de Jalapa 
            ['id_municipio' => 307, 'id_departamento' => 21, 'nombre_municipio' => 'Jalapa'],
            ['id_municipio' => 308, 'id_departamento' => 21, 'nombre_municipio' => 'San Pedro Pinula'],
            ['id_municipio' => 309, 'id_departamento' => 21, 'nombre_municipio' => 'San Luis Jilotepeque'],
            ['id_municipio' => 310, 'id_departamento' => 21, 'nombre_municipio' => 'San Manuel Chaparrón'],
            ['id_municipio' => 311, 'id_departamento' => 21, 'nombre_municipio' => 'San Carlos Alzatate'],
            ['id_municipio' => 312, 'id_departamento' => 21, 'nombre_municipio' => 'Monjas'],
            ['id_municipio' => 313, 'id_departamento' => 21, 'nombre_municipio' => 'Mataquescuintla'],

            //Jutiapa
            ['id_municipio' => 314, 'id_departamento' => 22, 'nombre_municipio' => 'Jutiapa'],
            ['id_municipio' => 315, 'id_departamento' => 22, 'nombre_municipio' => 'El Progreso'],
            ['id_municipio' => 316, 'id_departamento' => 22, 'nombre_municipio' => 'Santa Catarina Mita'],
            ['id_municipio' => 317, 'id_departamento' => 22, 'nombre_municipio' => 'Agua Blanca'],
            ['id_municipio' => 318, 'id_departamento' => 22, 'nombre_municipio' => 'Asunción Mita'],
            ['id_municipio' => 319, 'id_departamento' => 22, 'nombre_municipio' => 'Yupiltepeque'],
            ['id_municipio' => 320, 'id_departamento' => 22, 'nombre_municipio' => 'Atescatempa'],
            ['id_municipio' => 321, 'id_departamento' => 22, 'nombre_municipio' => 'Jerez'],
            ['id_municipio' => 322, 'id_departamento' => 22, 'nombre_municipio' => 'El Adelanto'],
            ['id_municipio' => 323, 'id_departamento' => 22, 'nombre_municipio' => 'Zapotitlán'],
            ['id_municipio' => 324, 'id_departamento' => 22, 'nombre_municipio' => 'Comapa'],
            ['id_municipio' => 325, 'id_departamento' => 22, 'nombre_municipio' => 'Jalpatagua'],
            ['id_municipio' => 326, 'id_departamento' => 22, 'nombre_municipio' => 'Conguaco'],
            ['id_municipio' => 327, 'id_departamento' => 22, 'nombre_municipio' => 'Moyuta'],
            ['id_municipio' => 328, 'id_departamento' => 22, 'nombre_municipio' => 'Pasaco'],
            ['id_municipio' => 329, 'id_departamento' => 22, 'nombre_municipio' => 'San José Acatempa'],
            ['id_municipio' => 330, 'id_departamento' => 22, 'nombre_municipio' => 'Quesada'],
        ]);
    }
}